name: production-deployment

on:
  push:
    branches: [ master ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest
    steps:
      - name: SSH remote command executer
        # You may pin to the exact commit or the version.
        uses: tarunjangra/ssh-remote-cmd@v1
        with:
          # Command to execute on the remote server.
          command: |
            cd /var/www/tools.cmlabs.co/
            sudo chown ubuntu:www-data -R ./
            git stash
            git stash clear
            git pull origin master
            composer install
            npm install
            npm run production
            php artisan queue:restart
            sudo chown www-data:www-data -R ./
            sudo chmod 775 -R storage public bootstrap/cache
          # Hostname or IP address of the server.
          host: ${{secrets.HOST_ADDRESS_PRODUCTION}}
          # Username for authentication to server.
          user: ${{secrets.HOST_USER_PRODUCTION}}
          # Port number of the server.
          port: 22
          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          key: ${{secrets.PRIVATE_KEY_PRODUCTION}}

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Tools (Production) Deployment
          url: ${{ secrets.MAIN_GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          if: always()
